### ISSUE TITLE
failed login

### ISSUE THREAD

**Issue by lostboy785** [zlepper/docker-solder#1]
Hey! Thanks for making the docker for Solder. I however cant log into the solder admin page. :(  

Error in exception handler.  is what I get every time I try to log into Solder.

I can log into GFS without issue

**Comment by zlepper** [comment]
Run the following command to put solder into debug mode:
```
docker exec CONTAINER_NAME sed -i.bak "s|'debug' => false|'debug' => true|g" /var/www/technicsolder/app/config/app.php
```
Then try to login again, and you should see the actual error.

And sorry for having you go the roundabout way, when i wrote that on technic forums i got hit with a security warning from cloudflare.

**Comment by lostboy785** [comment]
No problems at all!

Error in exception handler: The stream or file "/var/www/technicsolder/app/storage/logs/solderlog-2017-08-13.txt" could not be opened: failed to open stream: Permission denied in /var/www/technicsolder/bootstrap/compiled.php:7116

**Comment by zlepper** [comment]
On the host, try running:
```
chmod -R 777 /path/to/storage/volume
```

where path to storage volume is where you volumed `/var/www/technicsolder/app/storage`

I have a feeling permissions on the host are confused. 


EDIT: Do you not have a volume enabled?

**Comment by lostboy785** [comment]
![hard to explain](https://user-images.githubusercontent.com/30983736/29252350-c182dca0-802a-11e7-98fe-a6a6d509218b.png)

This looks like a step forward.

**Comment by zlepper** [comment]
Well, i can say i have seen the issue before, and fixed it, but can't remember how right now...

Try doing the above permission trick to the `/var/lib/postgresql/data` volume, and then restart the container. I'm not sure that will fix the issue, but i have a hunch

**Comment by lostboy785** [comment]
chmod -R 777 /var/lib/postgresql/data                         chmod: cannot access '/var/lib/postgresql/data': No such file or directory

Something I have to do to run this in the docker session?

**Comment by zlepper** [comment]
That should also be run on the host, and it's a volume like the above mentioned storage volume, so the actual path should be where you are voluming that.

**Comment by lostboy785** [comment]
Hrm I am sorry I am mostly new to docker.  I am not finding /var/lib/postgresql/data under my folder for my docker instance.
I do have a /data/docker/solder/database

**Comment by zlepper** [comment]
Alright, what was the entire command you ran to start the container (Removing any sensitive information like passwords)?

**Comment by lostboy785** [comment]
docker run -d --name=solder \
    -p 80:80 -p 8080:8080 \
    -v /data/docker/solder/database:/var/lib/postgresql/data \
    -v /data/docker/solder/repo:/var/www/repo.solder \
    -v /data/docker/solder/storage:/var/www/technicsolder/app/storage \
    -e "SOLDER_HOST=solder.tnnl.net" \
    -e "REPO_HOST=repo.tnnl.net" \
    -e "REPO_USER=Username" \
    -e "REPO_PASSWORD=Password" \
    zlepper/solder

**Comment by zlepper** [comment]
Alright, so the
```
-v /data/docker/solder/database:/var/lib/postgresql/data 
```
part of the command creates what is called a volume. In essense this tells docker that the `/var/lib/postgresql/data` folder in the container should actually look at the data at `/data/docker/solder/database` on the host. 
This ensures that the data is still available, should you ever need to update the container (Which in docker is done by removing the old one, and creating a new one)

Therefore you should run the chmod command as such:
```
chmod -R 777 /data/docker/solder/database
```

**Comment by lostboy785** [comment]
Ran the command with the same response. Just doing a little bit of googling looks like the DB username and password are not correct.

**Comment by zlepper** [comment]
Can you get me the output of `docker lige SOLDER_CONTAINER`? It might have some hint as to why that would be failing, considering the password is being set on startup.

**Comment by zlepper** [comment]
docker logs, not docker like


FFS auto correct

**Comment by lostboy785** [comment]
http://repo.tnnl.net/
Configuring solder
mkdir: can't create directory '/var/www/technicsolder/app/storage/meta': File ex                                                                                        ists
mkdir: can't create directory '/var/www/technicsolder/app/storage/views': File e                                                                                        xists
mkdir: can't create directory '/var/www/technicsolder/app/storage/sessions': Fil                                                                                        e exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/resources': Fi                                                                                        le exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/logs': File ex                                                                                        ists
mkdir: can't create directory '/var/www/technicsolder/app/storage/github-api-cac                                                                                        he': File exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/debugbar': Fil                                                                                        e exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/cache': File e                                                                                        xists
LOG:  database system was interrupted; last known up at 2017-08-13 18:42:22 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
Running php artisan migrate:install
LOG:  invalid record length at 0/15B4920: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "root" does not exist


  [PDOException]
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist


migrate:install [--database [DATABASE]]

Running actual migration
FATAL:  role "root" does not exist


  [PDOException]
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist


migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]] [--p                                                                                        ackage [PACKAGE]] [--pretend] [--seed]

mkdir: can't create directory '/var/www/repo.solder': File exists
2017/08/13 18:52:58 Config file didn't exist, defaulting
2017/08/13 18:52:59 Updated configs. Start gfs without the `persist` flag to sta                                                                                        rt the program.
Starting nginx
2017/08/13 18:52:59 {lost $2a$12$trlBaN5sQD8m0DA9gksuoey8OIKP3MUXThHKZ9b.3bx8tZk                                                                                        foD16O /var/www/repo.solder 8080 556568fe-8781-462b-aae9-70d145bc2282 false}
2017/08/13 18:52:59 No new version available
FATAL:  role "nobody" does not exist
FATAL:  role "nobody" does not exist
2017/08/13 18:59:25 Login successful
2017/08/13 18:59:26 Could not find known format in accepts. Hoping for the best.                                                                                         Request accept header: image/webp,image/apng,image/*,*/*;q=0.8
2017/08/13 18:59:26 Unknown response format
FATAL:  role "nobody" does not exist
FATAL:  role "nobody" does not exist
mkdir: can't create directory '/run/postgresql': File exists
http://repo.tnnl.net/
Configuring solder
mkdir: can't create directory '/var/www/technicsolder/app/storage/meta': File ex                                                                                        ists
mkdir: can't create directory '/var/www/technicsolder/app/storage/views': File e                                                                                        xists
mkdir: can't create directory '/var/www/technicsolder/app/storage/sessions': Fil                                                                                        e exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/resources': Fi                                                                                        le exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/logs': File ex                                                                                        ists
mkdir: can't create directory '/var/www/technicsolder/app/storage/github-api-cac                                                                                        he': File exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/debugbar': Fil                                                                                        e exists
mkdir: can't create directory '/var/www/technicsolder/app/storage/cache': File e                                                                                        xists
Running php artisan migrate:install
LOG:  database system was interrupted; last known up at 2017-08-13 18:52:58 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/15B4990: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "root" does not exist


  [PDOException]
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist


migrate:install [--database [DATABASE]]

Running actual migration
FATAL:  role "root" does not exist


  [PDOException]
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist


migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]] [--p                                                                                        ackage [PACKAGE]] [--pretend] [--seed]

mkdir: can't create directory '/var/run/php': File exists
mkdir: can't create directory '/var/log/nginx/technicsolder': File exists
mkdir: can't create directory '/run/nginx': File exists
mkdir: can't create directory '/var/www/repo.solder': File exists
mkdir: can't create directory '/var/log/nginx/repo.solder': File exists
2017/08/13 19:00:55 Updated configs. Start gfs without the `persist` flag to sta                                                                                        rt the program.
Starting nginx
2017/08/13 19:00:55 {lost $2a$12$SEflcoVjE6Rfvc1QVzzrO.Ac6TK9k/ndrOl4gqPmntpU/93                                                                                        6eSNJO /var/www/repo.solder 8080 556568fe-8781-462b-aae9-70d145bc2282 false}
2017/08/13 19:00:55 No new version available
FATAL:  role "nobody" does not exist
FATAL:  role "nobody" does not exist
FATAL:  role "nobody" does not exist
root@Solder-01:/data/docker/solder/database#

**Comment by zlepper** [comment]
Well, something is very wrong on your system... I don't know if the permissions were messed up or what, but something has gone haywire with postgres. 
Try the following steps:
1. Delete the container
2. Remove the /data/docker/solder directory (rm -rf /data/docker/solder)
3. Recreate the container using your above command

I just tried on a fresh digital ocean droplet, running your command (with the SOLDER_HOST and REPO_HOST tweaked worked without a hitch, as you can see here: <http://solder3.zlepper.dk>)

**Comment by lostboy785** [comment]
Hot dog! I am in.  So I am going to guess it had to do with the rights applied to the folder docker was putting files during the first startup.

Thank you for your help and again thank you for making this in docker to making standing it up faster.

**Comment by zlepper** [comment]
Yeah, they can be a pain in the butt. 

If you find any other issues (You likely will, as i'm mostly using this image for developing modpack-packer), then please report them here, and i'll try to fix them as fast as possible :)

If there if nothing else, then please close the issue :)
